src/Entity/Fruit.php
<?php

namespace App\Entity;

use App\Repository\FruitRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
// use Doctrine\Common\Collections\Collection;
use App\Entity\Nutrition;

/**
 * @ORM\Entity(repositoryClass=FruitRepository::class)
 */
class Fruit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $genus;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $family;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $fruitOrder;

    /**
     * @ORM\OneToOne(targetEntity="Nutrition", inversedBy="fruit")
     * @ORM\JoinColumn(name="nutrition_id", referencedColumnName="id")
     */
    private $nutrition;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGenus(): ?string
    {
        return $this->genus;
    }

    public function setGenus(string $genus): self
    {
        $this->genus = $genus;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFamily(): ?string
    {
        return $this->family;
    }

    public function setFamily(string $family): self
    {
        $this->family = $family;

        return $this;
    }

    public function getOrder(): ?string
    {
        return $this->fruitOrder;
    }

    public function setOrder(string $fruitOrder): self
    {
        $this->fruitOrder = $fruitOrder;

        return $this;
    }

    /**
     * Get the value of nutrition
     */ 
    public function getNutrition()
    {
        return $this->nutrition;
    }

    /**
     * Set the value of nutrition
     *
     * @return  self
     */ 
    public function setNutrition($nutrition)
    {
        $this->nutrition = $nutrition;

        return $this;
    }
}

src/Entity/Nutrition.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\NutritionRepository")
 */
class Nutrition
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $carbohydrates;

    /**
     * @ORM\Column(type="float")
     */
    private $protein;

    /**
     * @ORM\Column(type="float")
     */
    private $fat;

    /**
     * @ORM\Column(type="float")
     */
    private $calories;

    /**
     * @ORM\Column(type="float")
     */
    private $sugar;

    /**
     * @ORM\OneToOne(targetEntity="Fruit", mappedBy="nutrition")
     */
    private $fruit;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCarbohydrates(): ?float
    {
        return $this->carbohydrates;
    }

    public function setCarbohydrates(float $carbohydrates): self
    {
        $this->carbohydrates = $carbohydrates;

        return $this;
    }

    public function getProtein(): ?float
    {
        return $this->protein;
    }

    public function setProtein(float $protein): self
    {
        $this->protein = $protein;

        return $this;
    }

    public function getFat(): ?float
    {
        return $this->fat;
    }

    public function setFat(float $fat): self
    {
        $this->fat = $fat;

        return $this;
    }

    public function getCalories(): ?float
    {
        return $this->calories;
    }

    public function setCalories(float $calories): self
    {
        $this->calories = $calories;

        return $this;
    }

    public function getSugar(): ?float
    {
        return $this->sugar;
    }

    public function setSugar(float $sugar): self
    {
        $this->sugar = $sugar;

        return $this;
    }

    public function getFruit()
    {
        return $this->fruit;
    }

    public function setFruit($fruit)
    {
        $this->fruit = $fruit;
    }
}

src/Controller/FruitController.php
<?php

namespace App\Controller;

use App\Entity\Fruit;
use App\Form\FruitType;
use App\Repository\FruitRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FruitController extends AbstractController
{
    /**
     * @Route("/", name="fruit_index")
     */
    public function index(Request $request, PaginatorInterface $paginator, FruitRepository $fruitRepository): Response
    {
        $data = $request->query->all();
        $name = $data['name'] ?? null;
        $family = $data['family'] ?? null;

        $queryBuilder = $fruitRepository->createQueryBuilder('f');

        if ($name) {
            $queryBuilder
                ->where('f.name LIKE :name')
                ->setParameter('name', '%'.$name.'%');
        }

        if ($family) {
            $queryBuilder
                ->andWhere('f.family LIKE :family')
                ->setParameter('family', '%'.$family.'%');
        }

        $pagination = $paginator->paginate(
            $queryBuilder,
            $request->query->getInt('page', 1),
            10
        );

        return $this->render('fruit/index.html.twig', [
            'fruits' => $pagination,
        ]);
    }

    /**
     * @Route("/fruit/{id}/add-to-favorites", name="fruit_add_to_favorites", methods={"POST"})
     */
    public function addToFavorites(Fruit $fruit, Request $request): Response
    {
        $session = $request->getSession();
        $favorites = $session->get('favorites', []);

        if (count($favorites) >= 10) {
            $this->addFlash('error', 'The favorites list is full. You cannot add more than 10 items.');
            return $this->redirectToRoute('fruit_index');
        }

        if (!in_array($fruit->getId(), $favorites)) {
            $favorites[] = $fruit->getId();
            $session->set('favorites', $favorites);
            $this->addFlash('success', 'The fruit has been added to favorites.');
        } else {
            $this->addFlash('warning', 'The fruit is already in favorites.');
        }

        return $this->redirectToRoute('fruit_index');
    }

    /**
     * @Route("/fruit/{id}/remove-from-favorites", name="fruit_remove_from_favorites", methods={"GET"})
     */
    public function removeFromFavorites(Fruit $fruit, Request $request): Response
    {
        $session = $request->getSession();
        $favorites = $session->get('favorites', []);

        $index = array_search($fruit->getId(), $favorites);
        if ($index !== false) {
            array_splice($favorites, $index, 1);
            $session->set('favorites', $favorites);
            $this->addFlash('success', 'The fruit has been removed from favorites.');
        } else {
            $this->addFlash('warning', 'The fruit is not in favorites.');
        }

        return $this->redirectToRoute('favorites');
    }

    /**
     * @Route("/favorites", name="favorites")
     */
    public function favorites(Request $request, FruitRepository $fruitRepository): Response
    {
        $session = $request->getSession();
        $favorites = $session->get('favorites', []);

        $fruits = $fruitRepository->findByIdWithNutrition($favorites);

        $totalNutritionFacts = [
            'carbohydrates' => 0,
            'proteins' => 0,
            'fat' => 0,
            'calories' => 0,
            'sugar' => 0
        ];

        foreach ($fruits as $fruit) {
            $totalNutritionFacts['carbohydrates'] += $fruit->getNutrition()->getCarbohydrates();
            $totalNutritionFacts['proteins'] += $fruit->getNutrition()->getProtein();
            $totalNutritionFacts['fat'] += $fruit->getNutrition()->getFat();
            $totalNutritionFacts['calories'] += $fruit->getNutrition()->getCalories();
            $totalNutritionFacts['sugar'] += $fruit->getNutrition()->getSugar();
        }

        // dd($fruits);

        return $this->render('fruit/favorites.html.twig', [
            'fruits' => $fruits,
            'totalNutritionFacts' => $totalNutritionFacts,
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{{ path('fruit_index') }}">Fruit App</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('fruit_index') }}">All Fruits</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ path('favorites') }}">My Favorites</a>
                    </li>
                </ul>
            </div>
        </nav>

        <div class="container my-5">
            {% block body %}{% endblock %}
        </div>

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNSwKkh" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        {% endblock %}
    </body>

</html>

templates/fruit/favorites.html.twig
{% extends 'base.html.twig' %}

{% block title %}Favorite Fruits{% endblock %}

{% block body %}
    <div class="container">
        <h1 class="text-center mb-4">Favorite Fruits</h1>
        <hr>

        {% if fruits|length > 0 %}
            <div class="row">
                {% for fruit in fruits %}
                    <div class="col-12 col-md-6 col-lg-4 mb-4">
                        <div class="card">
                            <div class="card-header text-center" title="Name">{{ fruit.name }}</div>
                            <div class="card-body">
                                <h5 class="card-title text-center" title="Family">{{ fruit.family }}</h5>
                                <hr>
                                <dl>
                                    <dt>Genus</dt>
                                    <dd>{{ fruit.genus }}</dd>
                                    <dt>Order</dt>
                                    <dd>{{ fruit.order }}</dd>
                                    <dt>Carbs</dt>
                                    <dd>{{ fruit.nutrition.carbohydrates }} g</dd>
                                    <dt>Fat</dt>
                                    <dd>{{ fruit.nutrition.fat }} g</dd>
                                    <dt>Protein</dt>
                                    <dd>{{ fruit.nutrition.protein }} g</dd>
                                </dl>
                                <a href="{{ path('fruit_remove_from_favorites', { id: fruit.id }) }}" class="btn btn-primary">Remove from Favorites</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>No favorite fruits yet.</p>
        {% endif %}

        {% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
        
        {% if totalNutritionFacts %}
            <div class="total-nutrition-facts bg-light p-4 mt-4">
                <h5>Total Nutrition Facts</h5>
                <hr>
                <p>Total carbohydrates: {{ totalNutritionFacts.carbohydrates }} g</p>
                <p>Total proteins: {{ totalNutritionFacts.proteins }} g</p>
                <p>Total fat: {{ totalNutritionFacts.fat }} g</p>
                <p>Total calories: {{ totalNutritionFacts.calories }} kcal</p>
                <p>Total sugars: {{ totalNutritionFacts.sugar }} g</p>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/fruit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fruits{% endblock %}

{% block stylesheets %}
    {# {{ parent() }} #}
    {# <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}"> #}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
{% endblock %}

{% block body %}
    <div class="container mt-4">
        <h1 class="text-center mb-5">All Fruits</h1>
        <div class="row justify-content-center">
            <div class="col-md-4">
                <form method="get" id="filter-form">
                    <div class="form-group">
                        <label for="name">Name:</label>
                        <input type="text" class="form-control" name="name" id="name" value="{{ app.request.query.get('name') }}">
                    </div>
                    <div class="form-group">
                        <label for="family">Family:</label>
                        <input type="text" class="form-control" name="family" id="family" value="{{ app.request.query.get('family') }}">
                    </div>
                    <button type="submit" class="btn btn-primary">Filter</button>
                    <a href="{{ path('fruit_index') }}" class="btn btn-secondary">Reset</a>
                </form>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-md-12">
                {% if fruits.getTotalItemCount() > 0 %}
                    <table class="table" id="fruits-table">
                        <thead>
                            <tr>
                                <th>Genus</th>
                                <th>Name</th>
                                <th>Family</th>
                                <th>Order</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for fruit in fruits %}
                                <tr>
                                    <td>

                                    {{ fruit.genus }}
                                    </td>
                                    <td>
                                    {{ fruit.name }}
                                    </td>
                                    <td>
                                    {{ fruit.family }}
                                    </td>
                                    <td>
                                    {{ fruit.order }}
                                    </td>
                                    <td>
                                        <form action="{{ path('fruit_add_to_favorites', {'id': fruit.id}) }}" method="post" class="d-inline">
                                            <button type="submit" class="btn btn-success btn-sm">Add to Favorites</button>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div class="d-flex justify-content-center">
                        {{ knp_pagination_render(fruits) }}
                    </div>
                    {% for message in app.flashes('success') %}
                        <div class="alert alert-success">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% else %}
                    <p>No fruits found.</p>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

{% block javascripts %}
    {# {{ parent() }} #}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#fruits-table').DataTable({
                "paging": false,
                "info": false,
                "searching": false,
            });

            $('#filter-form').submit(function (event) {
                event.preventDefault();

                var name = $('#name').val();
                var family = $('#family').val();

                var url = "{{ path('fruit_index') }}";
                if (name || family) {
                    url += "?";
                    if (name) {
                        url += "name=" + encodeURIComponent(name) + "&";
                    }
                    if (family) {
                        url += "family=" + encodeURIComponent(family) + "&";
                    }
                    url = url.slice(0, -1);
                }

                window.location.href = url;
            });
        });
    </script>
{% endblock %}